services:
  cli-weather:
    image: ghcr.io/c1aytonnet/cli-weather:latest
    env_file:
      - ./cli-weather/.env
    environment:
      CLI_WEATHER_CONFIG_DIR: /data
    volumes:
      - ./cli-weather:/data
    command: ["cli-weather", "--help"]

  cli-weather-scheduler:
    image: ghcr.io/c1aytonnet/cli-weather:latest
    env_file:
      - ./cli-weather/.env
    environment:
      CLI_WEATHER_CONFIG_DIR: /data
    volumes:
      - ./cli-weather:/data
    entrypoint: ["/app/docker/scheduler-entrypoint.sh"]
    restart: unless-stopped
    profiles: ["scheduler"]
